:PROPERTIES:
:Title:    Algorithms and data structures
:Author:   pjsamm
:Date:     2026-01-20
:Category: Notes
:Abstract: Notes on fundamental algorithms and data structures in computer science.
:END:

#+INCLUDE: ".global_options"

**** TODO Cite Intro to Algorithms textbook used as source        :easy:high:
**** TODO Convert to proper C library                              :hard:low:
**** TODO Add inline math markup where appropriate                 :easy:low:

* Overview

**** TODO Insert definition markup once supported                  :easy:low:

An algorithm is a sequence of computational steps that transforms
input into output according to a certain input/output relationship
(the problem statement).

An algorithm is considered correct if, for every possible input, it
halts with the correct output (as defined by the problem
statement). Note that "incorrect" algorithms can still be useful.

* Analysis

**** TODO Move 'foundations' into its own page(s)?                 :easy:low:

** Foundations

** Asymptotic notation

*** Big O notation

*** Big theta notation

** Amortized analysis

** NP-completeness

* Data structures

** Dynamic array

** Stack

A *stack* is a last-in, first-out (LIFO) data structure.

#+begin_src python
  class Stack:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.top = -1

      def push(self, x):
          if self.top >= self.cap:
              raise Exception('Stack overflow')
          self.top += 1
          self.items[self.top] = x

      def pop(self):
          if self.top < 0:
              raise Exception('Stack underflow')
          self.top -= 1
          return self.items[self.top + 1]
#+end_src

** Queue

A *queue* is a first-in, first-out (FIFO) data structure.

#+begin_src python
  class Queue:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.head = self.tail = 0

      def enqueue(self, x):
          if (self.tail + 1) % self.cap == self.head:
              raise Exception('Queue overflow')
          self.items[self.tail] = x
          if self.tail >= self.cap - 1:
              self.tail = 0
          else:
              self.tail += 1

      def dequeue(self):
          if self.head == self.tail:
              raise Exception('Queue underflow')
          x = self.items[self.head]
          if self.head >= self.cap - 1:
              self.head = 0
          else:
              self.head += 1
          return x
#+end_src

*** Priority queues

*** Double-ended queue

Also known as a *deque*.

** Linked list

*** Singly linked list

*** Doubly linked list

** Hash table

alpha: load factor
n: number of elements
m: number of slots
alpha = n / m

*** Hash function

Division method: h(k) = k mod m

Multiplication method: h(k) = floor(m * (k * A - floor(k * A))), 0 < A < 1

Universal hashing

*** Chaining

*** Open addressing

Linear probing

Quadratic probing

Double hashing

** Heap

*** Mergeable heap

*** Binomial heap

*** Fibonacci heap

** Tree

*** Binary search tree

Randomly built BST

*** Red-black tree

1. Every node is either red or black.
2. Every leaf (null child) is black.
3. If a node is red, both its children are black.
4. Every path from a node to a leaf contains the same number of black nodes.

Insertion:
1. Insert new node as normal in BST with color red
2. If property 3 is violated (because the new node's parent is red),
   move up the tree while maintaining property 4 as an invariant

*** AVL tree

*** B-tree and B+-tree

** Graph

* Sorting

#+INCLUDE: "algorithms_and_data_structures/#sorting.org" :minlevel 2

* Searching

** Linear search

** Binary search

** Breadth-first search

** Depth-first search

* Path finding

** Dijkstra's algorithm

** A*

* Miscellaneous

** Dynamic programming

** Greedy algorithms

** Disjoint sets

** Minimum and maximum

** Dynamic order statistics

** Dynamic intervals

** Selection

