:PROPERTIES:
:Title:    Algorithms and data structures
:Author:   pjsamm
:Date:     2026-01-20
:Category: Notes
:Abstract: Notes on fundamental algorithms and data structures in computer science.
:END:

#+OPTIONS: H:5
#+OPTIONS: ^:{}

#+PROPERTY: header-args    :noweb yes
#+PROPERTY: header-args+   :eval never-export

**** TODO Cite Intro to Algorithms textbook used as source        :easy:high:
**** TODO Convert to proper C library                              :hard:low:
**** TODO Add inline math markup where appropriate                 :easy:low:

* Overview

**** TODO Insert definition markup once supported                  :easy:low:

An algorithm is a sequence of computational steps that transforms
input into output according to a certain input/output relationship
(the problem statement).

An algorithm is considered correct if, for every possible input, it
halts with the correct output (as defined by the problem
statement). Note that "incorrect" algorithms can still be useful.

* Analysis

**** TODO Move 'foundations' into its own page(s)?                 :easy:low:

** Foundations

** Asymptotic notation

*** Big O notation

*** Big theta notation

** Amortized analysis

** NP-completeness

* Data structures

** Dynamic array

** Stack

A *stack* is a last-in, first-out (LIFO) data structure.

#+begin_src python
  class Stack:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.top = -1

      def push(self, x):
          if self.top >= self.cap:
              raise Exception('Stack overflow')
          self.top += 1
          self.items[self.top] = x

      def pop(self):
          if self.top < 0:
              raise Exception('Stack underflow')
          self.top -= 1
          return self.items[self.top + 1]
#+end_src

** Queue

A *queue* is a first-in, first-out (FIFO) data structure.

#+begin_src python
  class Queue:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.head = self.tail = 0

      def enqueue(self, x):
          if (self.tail + 1) % self.cap == self.head:
              raise Exception('Queue overflow')
          self.items[self.tail] = x
          if self.tail >= self.cap - 1:
              self.tail = 0
          else:
              self.tail += 1

      def dequeue(self):
          if self.head == self.tail:
              raise Exception('Queue underflow')
          x = self.items[self.head]
          if self.head >= self.cap - 1:
              self.head = 0
          else:
              self.head += 1
          return x
#+end_src

*** Priority queues

*** Double-ended queue

** Linked list

** Hash table

** Heap

*** Binomial heap

*** Fibonacci heap

** Tree

*** Binary search tree

*** Red-black tree

*** AVL tree

*** B-tree and B+-tree

** Graph

* Sorting

The sorting problem takes as input a sequence of n numbers and returns
as output a permutation of said sequence such that each element is
less than or equal to the next element.

** Insertion sort

**** TODO Better handling of examples/unit tests                    :med:mid:
**** TODO Better handling of in-place nature of algorithm          :easy:mid:
**** TODO Nicer printing of results                                :easy:low:

#+begin_src python :results output
  def insertion_sort(array):
      for i in range(1, len(array)):
          key = array[i]
          j = i - 1
          while j >= 0 and key < array[j]:
              array[j + 1] = array[j]
              j -= 1
          array[j + 1] = key
      return array

  print(insertion_sort([5, 2, 4, 6, 1, 3]))
  print(insertion_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

** Merge sort

#+begin_src python :results output
  def merge_sort(array):
      n = len(array)
      if n <= 1:
          return array

      list1 = array[:n // 2]
      list2 = array[n // 2:]

      merge_sort(list1)
      merge_sort(list2)

      i = 0
      j = 0
      while i + j < n:
          if j >= (n - n // 2) or (i < n//2 and list1[i] < list2[j]):
              array[i + j] = list1[i]
              i += 1
          else:
              array[i + j] = list2[j]
              j += 1
              
      return array

  print(merge_sort([5, 2, 4, 6, 1, 3]))
  print(merge_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

** Heapsort

** Quicksort

#+begin_src python :results output
  def quick_sort(array):
      def _quick_sort(array, start, end):
          if start >= end:
              return

          pivot = array[start]

          i = start + 1
          j = end
          while True:
              while i <= end and array[i] <= pivot:
                  i += 1
              while j > start and array[j] >= pivot:
                  j -= 1

              if j < i:
                  break

              temp = array[i]
              array[i] = array[j]
              array[j] = temp

          if j > start:
              array[start] = array[j]
              array[j] = pivot

          _quick_sort(array, start, j)
          _quick_sort(array, j + 1, end)

      _quick_sort(array, 0, len(array) - 1)
      return array

  print(quick_sort([5, 2, 4, 6, 1, 3]))
  print(quick_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

** Counting sort

** Radix sort

** Bucket sort

* Searching

** Linear search

** Binary search

** Breadth-first search

** Depth-first search

* Path finding

** Dijkstra's algorithm

** A*

* Miscellaneous

** Dynamic programming

** Greedy algorithms

** Disjoint sets

** Minimum and maximum

** Selection

