:PROPERTIES:
:Title:    Algorithms and data structures
:Author:   pjsamm
:Date:     2026-01-20
:Category: Notes
:Abstract: Notes on fundamental algorithms and data structures in computer science.
:END:

#+INCLUDE: "global_options.org"

**** TODO Cite Intro to Algorithms textbook used as source        :easy:high:
**** TODO Convert to proper C library                              :hard:low:
**** TODO Add inline math markup where appropriate                 :easy:low:

* Overview

**** TODO Insert definition markup once supported                  :easy:low:

An algorithm is a sequence of computational steps that transforms
input into output according to a certain input/output relationship
(the problem statement).

An algorithm is considered correct if, for every possible input, it
halts with the correct output (as defined by the problem
statement). Note that "incorrect" algorithms can still be useful.

* Analysis

**** TODO Move 'foundations' into its own page(s)?                 :easy:low:

** Foundations

** Asymptotic notation

*** Big O notation

*** Big theta notation

** Amortized analysis

** NP-completeness

* Data structures

** Dynamic array

** Stack

A *stack* is a last-in, first-out (LIFO) data structure.

#+begin_src python
  class Stack:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.top = -1

      def push(self, x):
          if self.top >= self.cap:
              raise Exception('Stack overflow')
          self.top += 1
          self.items[self.top] = x

      def pop(self):
          if self.top < 0:
              raise Exception('Stack underflow')
          self.top -= 1
          return self.items[self.top + 1]
#+end_src

** Queue

A *queue* is a first-in, first-out (FIFO) data structure.

#+begin_src python
  class Queue:
      def __init__(self, n):
          self.cap = n
          self.items = [None] * n
          self.head = self.tail = 0

      def enqueue(self, x):
          if (self.tail + 1) % self.cap == self.head:
              raise Exception('Queue overflow')
          self.items[self.tail] = x
          if self.tail >= self.cap - 1:
              self.tail = 0
          else:
              self.tail += 1

      def dequeue(self):
          if self.head == self.tail:
              raise Exception('Queue underflow')
          x = self.items[self.head]
          if self.head >= self.cap - 1:
              self.head = 0
          else:
              self.head += 1
          return x
#+end_src

*** Priority queues

*** Double-ended queue

Also known as a *deque*.

** Linked list

*** Singly linked list

*** Doubly linked list

** Hash table

alpha: load factor
n: number of elements
m: number of slots
alpha = n / m

*** Hash function

Division method: h(k) = k mod m

Multiplication method: h(k) = floor(m * (k * A - floor(k * A))), 0 < A < 1

Universal hashing

*** Chaining

*** Open addressing

Linear probing

Quadratic probing

Double hashing

** Heap

*** Mergeable heap

*** Binomial heap

*** Fibonacci heap

** Tree

*** Binary search tree

Randomly built BST

*** Red-black tree

1. Every node is either red or black.
2. Every leaf (null child) is black.
3. If a node is red, both its children are black.
4. Every path from a node to a leaf contains the same number of black nodes.

Insertion:
1. Insert new node as normal in BST with color red
2. If property 3 is violated (because the new node's parent is red),
   move up the tree while maintaining property 4 as an invariant

*** AVL tree

*** B-tree and B+-tree

** Graph

* Sorting

**** TODO Add complexity comparison table                         :easy:high:

The sorting problem takes as input a sequence of n numbers and returns
as output a permutation of said sequence such that each element is
less than or equal to the next element.

** Comparison sort

*** Insertion sort

**** TODO Better handling of examples/unit tests                    :med:mid:
**** TODO Better handling of in-place nature of algorithm          :easy:mid:
**** TODO Nicer printing of results                                :easy:low:

#+begin_src python :results output
  def insertion_sort(array):
      for i in range(1, len(array)):
          key = array[i]
          j = i - 1
          while j >= 0 and key < array[j]:
              array[j + 1] = array[j]
              j -= 1
          array[j + 1] = key
      return array

  print(insertion_sort([5, 2, 4, 6, 1, 3]))
  print(insertion_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

*** Merge sort

#+begin_src python :results output
  def merge_sort(array):
      if len(array) <= 1:
          return array

      mid = len(array) // 2
      left = array[:mid]
      right = array[mid:]

      merge_sort(left)
      merge_sort(right)

      i = j = 0
      while i < len(left) and j < len(right):
          if left[i] < right[j]:
              array[i + j] = left[i]
              i += 1
          else:
              array[i + j] = right[j]
              j += 1

      while i < len(left):
          array[i + j] = left[i]
          i += 1

      while j < len(right):
          array[i + j] = right[j]
          j += 1

      return array

  print(merge_sort([5, 2, 4, 6, 1, 3]))
  print(merge_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

*** Heapsort

*** Quicksort

#+begin_src python :results output
  def quick_sort(array):
      def _quick_sort(array, start, end):
          if start >= end:
              return

          pivot = array[start]
          i = start + 1
          j = end
          
          while True:
              while i <= end and array[i] <= pivot:
                  i += 1
              while j > start and array[j] >= pivot:
                  j -= 1

              if j < i:
                  break

              array[i], array[j] = array[j], array[i]

          array[start], array[j] = array[j], array[start]

          _quick_sort(array, start, j - 1)
          _quick_sort(array, j + 1, end)

      _quick_sort(array, 0, len(array) - 1)
      return array

  print(quick_sort([5, 2, 4, 6, 1, 3]))
  print(quick_sort([31, 41, 59, 26, 41, 58]))
#+end_src

#+RESULTS:
: [1, 2, 3, 4, 5, 6]
: [26, 31, 41, 41, 58, 59]

** Distribution sort

*** Counting sort

*** Radix sort

*** Bucket sort

* Searching

** Linear search

** Binary search

** Breadth-first search

** Depth-first search

* Path finding

** Dijkstra's algorithm

** A*

* Miscellaneous

** Dynamic programming

** Greedy algorithms

** Disjoint sets

** Minimum and maximum

** Dynamic order statistics

** Dynamic intervals

** Selection

