:PROPERTIES:
:Title:    Nand to Tetris
:Author:   pjsamm
:Date:     2026-02-07
:Category: Project
:Abstract: My implementation of the nand2tetris course.
:END:

#+INCLUDE: "../global_options.org"

**** TODO Add symbolic derivations of chips                        :easy:mid:

* Logic gates

**** TODO Consistent capitalization                                :easy:low:
**** TODO Split into subfile w/ better organization                :easy:mid:

** Nand & Nor

~NAND~ and ~NOR~ are the only two functionally complete logical
connectives; that is, any possible truth table can be produced using
only ~NAND~ (or ~NOR~) gates.

Their truth tables are as follows:

#+name: NAND truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   1 |
| 1 | 0 |   1 |
| 0 | 1 |   1 |
| 1 | 1 |   0 |

#+name: NOR truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   1 |
| 1 | 0 |   0 |
| 0 | 1 |   0 |
| 1 | 1 |   0 |

Since they are each functionally complete, each can be written in
terms of the other, like so:

#+name: NOR in terms of NAND
#+begin_src java
  CHIP Nor {
      IN a, b;
      OUT out;

      PARTS:
      Nand(a=a, b=a, out=i1);
      Nand(a=b, b=b, out=i2);
      Nand(a=i1, b=i2, out=i3);
      Nand(a=i3, b=i3, out=out);
  }
#+end_src

#+name: NAND in terms of NOR
#+begin_src java
  CHIP Nand {
      IN a, b;
      OUT out;

      PARTS:
      Nor(a=a, b=a, out=i1);
      Nor(a=b, b=b, out=i2);
      Nor(a=i1, b=i2, out=i3);
      Nor(a=i3, b=i3, out=out);
  }
#+end_src

As you can see, the constructions are identical apart from exchanging
the gate names. In particular, both use the fact that a single line
connected to both inputs inverts the line. Speaking of which...

** Not

~NOT~ is the only unary gate of interest (the only other possibilities
being pass-through or constant gates). It has the following truth
table:

#+name: NOT truth table
| in | out |
|----+-----|
|  0 |   1 |
|  1 |   0 |

As suggested at the end of the previous section, this can be achieved
using ~NAND~ or ~NOR~ by simply connecting the same value to both
inputs.

#+name: NOT in terms of NAND
#+begin_src java
  CHIP Not {
      IN in;
      OUT out;

      PARTS:
      Nand(a=in, b=in, out=out);
  }
#+end_src

Again, the case for ~NOR~ is identical apart from the gate name and so
is omitted.

For clarity, I will use ~NOT x~ rather than ~x NAND x~ or ~x NOR x~
going forward.

** And

The truth table for AND is:

#+name: AND truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   0 |
| 1 | 0 |   0 |
| 0 | 1 |   0 |
| 1 | 1 |   1 |

Construction using ~NAND~ is simple, considering ~NAND~ is just
inverted ~AND~:

#+name: AND in terms of NAND
#+begin_src java
  CHIP And {
      IN a, b;
      OUT out;
    
      PARTS:
      Nand(a=a, b=b, out=i1);
      Not(in=i1, out=out);
  }
#+end_src

Construction using ~NOR~ is slightly more complex, requiring both
inputs to be inverted rather than the output:

#+name: AND in terms of NOR
#+begin_src java
  CHIP And {
      IN a, b;
      OUT out;

      PARTS:
      Not(in=a, out=i1);
      Not(in=b, out=i2);
      Nor(a=i1, b=i2, out=out);
  }
#+end_src

** Or

~OR~ has the following truth table:

#+name: OR truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   0 |
| 0 | 1 |   1 |
| 1 | 0 |   1 |
| 1 | 1 |   1 |

This time, it is ~NAND~ that requires the inverted inputs, while ~NOR~
need only invert the output:

#+name: OR in terms of NAND
#+begin_src java
  CHIP Or {
      IN a, b;
      OUT out;

      PARTS:
      Not(in=a, out=i1);
      Not(in=b, out=i2);
      Nand(a=i1, b=i2, out=out);
  }
#+end_src

#+name: OR in terms of NOR
#+begin_src java
  CHIP Or {
      IN a, b;
      OUT out;

      PARTS:
      Nor(a=a, b=b, out=i1);
      Not(in=i1, out=out);
  }
#+end_src

** Xor

Starting with ~XOR~, I will only be considering constructions using
~NAND~ for simplicity.

~XOR~ has the following truth table:

#+name: XOR truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   0 |
| 1 | 0 |   1 |
| 0 | 1 |   1 |
| 1 | 1 |   0 |

While a straightforward construction using ~NAND~ will often use 5
gates, the minimum number of ~NAND~ gates needed is just 4:

#+name: XOR in terms of NAND
#+begin_src java
  CHIP Xor {
      IN a, b;
      OUT out;

      PARTS:
      Nand(a=a, b=b, out=i1);
      Nand(a=a, b=i1, out=i2);
      Nand(a=b, b=i1, out=i3);
      Nand(a=i2, b=i3, out=out);
  }
#+end_src

** Xnor

~XNOR~ (a.k.a. ~EQ~) has the following truth table:

#+name: XNOR truth table
| a | b | out |
|---+---+-----|
| 0 | 0 |   1 |
| 1 | 0 |   0 |
| 0 | 1 |   0 |
| 1 | 1 |   1 |

Though simple to derive, it has the most complex construction of the
binary connectives (using ~NAND~) at 5 gates:

#+name: XNOR in terms of NAND
#+begin_src java
  CHIP Xnor {
      IN a, b;
      OUT out;

      PARTS:
      Not(in=a, out=i1);
      Not(in=b, out=i2);
      Nand(a=i1, b=i2, out=i3);
      Nand(a=a, b=b, out=i4);
      Nand(a=i3, b=i4, out=out);
  }
#+end_src

** Mux

From here, we move to higher order gates, starting with ~MUX~
(i.e. "multiplexor"), which uses one input to select between two other
inputs:

#+name: MUX truth table
| sel | out |
|-----+-----|
|   0 | a   |
|   1 | b   |

#+name: MUX in terms of NAND
#+begin_src java
  CHIP Mux {
      IN a, b, sel;
      OUT out;

      PARTS:
      Not(in=sel, out=nsel);
      Nand(a=a, b=nsel, out=i1);
      Nand(a=b, b=sel, out=i2);
      Nand(a=i1, b=i2, out=out);
  }
#+end_src

** Dmux

~DMUX~, on the other hand, uses one input to select which of two
output lines its other input should appear on:

#+name: MUX truth table
| sel | a  | b  |
|-----+----+----|
|   0 | in | 0  |
|   1 | 0  | in |

#+name: DMUX in terms of NAND
#+begin_src java
  CHIP DMux {
      IN in, sel;
      OUT a, b;

      PARTS:
      Not(in=sel, out=nsel);
      Nand(a=in, b=nsel, out=i1);
      Not(in=i1, out=a);
      Nand(a=in, b=sel, out=i2);
      Not(in=i2, out=b);
  }
#+end_src

** Not16

~NOT16~ takes a 16-bit input an inverts each individual bit:

#+begin_src java
  CHIP Not16 {
      IN in[16];
      OUT out[16];

      PARTS:
      Not(in=in[0], out=out[0]);
      Not(in=in[1], out=out[1]);
      Not(in=in[2], out=out[2]);
      Not(in=in[3], out=out[3]);
      Not(in=in[4], out=out[4]);
      Not(in=in[5], out=out[5]);
      Not(in=in[6], out=out[6]);
      Not(in=in[7], out=out[7]);
      Not(in=in[8], out=out[8]);
      Not(in=in[9], out=out[9]);
      Not(in=in[10], out=out[10]);
      Not(in=in[11], out=out[11]);
      Not(in=in[12], out=out[12]);
      Not(in=in[13], out=out[13]);
      Not(in=in[14], out=out[14]);
      Not(in=in[15], out=out[15]);
  }
#+end_src

** And16

~AND16~ takes two 16-bit inputs and computes their bitwise ~AND~:

#+begin_src java
  CHIP And16 {
      IN a[16], b[16];
      OUT out[16];

      PARTS:
      And(a=a[0], b=b[0], out=out[0]);
      And(a=a[1], b=b[1], out=out[1]);
      And(a=a[2], b=b[2], out=out[2]);
      And(a=a[3], b=b[3], out=out[3]);
      And(a=a[4], b=b[4], out=out[4]);
      And(a=a[5], b=b[5], out=out[5]);
      And(a=a[6], b=b[6], out=out[6]);
      And(a=a[7], b=b[7], out=out[7]);
      And(a=a[8], b=b[8], out=out[8]);
      And(a=a[9], b=b[9], out=out[9]);
      And(a=a[10], b=b[10], out=out[10]);
      And(a=a[11], b=b[11], out=out[11]);
      And(a=a[12], b=b[12], out=out[12]);
      And(a=a[13], b=b[13], out=out[13]);
      And(a=a[14], b=b[14], out=out[14]);
      And(a=a[15], b=b[15], out=out[15]);
  }
#+end_src

** Or16

Similarly, ~OR16~ takes two 16-bit inputs and computes their bitwise ~OR~:

#+begin_src java
  CHIP Or16 {
      IN a[16], b[16];
      OUT out[16];

      PARTS:
      Or(a=a[0], b=b[0], out=out[0]);
      Or(a=a[1], b=b[1], out=out[1]);
      Or(a=a[2], b=b[2], out=out[2]);
      Or(a=a[3], b=b[3], out=out[3]);
      Or(a=a[4], b=b[4], out=out[4]);
      Or(a=a[5], b=b[5], out=out[5]);
      Or(a=a[6], b=b[6], out=out[6]);
      Or(a=a[7], b=b[7], out=out[7]);
      Or(a=a[8], b=b[8], out=out[8]);
      Or(a=a[9], b=b[9], out=out[9]);
      Or(a=a[10], b=b[10], out=out[10]);
      Or(a=a[11], b=b[11], out=out[11]);
      Or(a=a[12], b=b[12], out=out[12]);
      Or(a=a[13], b=b[13], out=out[13]);
      Or(a=a[14], b=b[14], out=out[14]);
      Or(a=a[15], b=b[15], out=out[15]);
  }
#+end_src

** Mux16

~MUX16~ takes two 16-bit inputs and a 1-bit input to select between them:

#+begin_src java
  CHIP Mux16 {
      IN a[16], b[16], sel;
      OUT out[16];

      PARTS:
      Mux(a=a[0], b=b[0], sel=sel, out=out[0]);
      Mux(a=a[1], b=b[1], sel=sel, out=out[1]);
      Mux(a=a[2], b=b[2], sel=sel, out=out[2]);
      Mux(a=a[3], b=b[3], sel=sel, out=out[3]);
      Mux(a=a[4], b=b[4], sel=sel, out=out[4]);
      Mux(a=a[5], b=b[5], sel=sel, out=out[5]);
      Mux(a=a[6], b=b[6], sel=sel, out=out[6]);
      Mux(a=a[7], b=b[7], sel=sel, out=out[7]);
      Mux(a=a[8], b=b[8], sel=sel, out=out[8]);
      Mux(a=a[9], b=b[9], sel=sel, out=out[9]);
      Mux(a=a[10], b=b[10], sel=sel, out=out[10]);
      Mux(a=a[11], b=b[11], sel=sel, out=out[11]);
      Mux(a=a[12], b=b[12], sel=sel, out=out[12]);
      Mux(a=a[13], b=b[13], sel=sel, out=out[13]);
      Mux(a=a[14], b=b[14], sel=sel, out=out[14]);
      Mux(a=a[15], b=b[15], sel=sel, out=out[15]);
  }
#+end_src

** Or8Way

~Or8Way~ emits 1 if any of its 8 inputs are 1 and 0 otherwise:

#+begin_src java
  CHIP Or8Way {
      IN in[8];
      OUT out;

      PARTS:
      Or(a=in[0], b=in[1], out=or1);
      Or(a=in[2], b=or1, out=or2);
      Or(a=in[3], b=or2, out=or3);
      Or(a=in[4], b=or3, out=or4);
      Or(a=in[5], b=or4, out=or5);
      Or(a=in[6], b=or5, out=or6);
      Or(a=in[7], b=or6, out=out);
  }
#+end_src

** Mux4Way16

~Mux4Way16~ uses a 2-bit input to select between four other 16-bit
inputs:

#+begin_src java
  CHIP Mux4Way16 {
      IN a[16], b[16], c[16], d[16], sel[2];
      OUT out[16];
    
      PARTS:
      Mux16(a=a, b=b, sel=sel[0], out=mux1);
      Mux16(a=c, b=d, sel=sel[0], out=mux2);
      Mux16(a=mux1, b=mux2, sel=sel[1], out=out);
  }
#+end_src

** Mux8Way16

Similarly, ~Mux8Way16~ uses a 2-bit input to select between eight
other 16-bit inputs:

#+begin_src java
  CHIP Mux8Way16 {
      IN a[16], b[16], c[16], d[16],
         e[16], f[16], g[16], h[16],
         sel[3];
      OUT out[16];

      PARTS:
      Mux4Way16(a=a, b=b, c=c, d=d, sel=sel[0..1], out=mux1);
      Mux4Way16(a=e, b=f, c=g, d=h, sel=sel[0..1], out=mux2);
      Mux16(a=mux1, b=mux2, sel=sel[2], out=out);
  }
#+end_src

** Dmux4Way

~Dmux4Way~ uses a 2-bit input to select which of four output lines its
other input should appear on:

#+begin_src java
  CHIP DMux4Way {
      IN in, sel[2];
      OUT a, b, c, d;

      PARTS:
      DMux(in=in, sel=sel[1], a=w1, b=w2);
      DMux(in=w1, sel=sel[0], a=a, b=b);
      DMux(in=w2, sel=sel[0], a=c, b=d);
  }
#+end_src

** Dmux8Way

And lastly, ~Dmux8Way~ uses a 3-bit input to select which of eight
output lines its other input should appear on:

#+begin_src java
  CHIP DMux8Way {
      IN in, sel[3];
      OUT a, b, c, d, e, f, g, h;

      PARTS:
      DMux(in=in, sel=sel[2], a=w1, b=w2);
      DMux4Way(in=w1, sel=sel[0..1], a=a, b=b, c=c, d=d);
      DMux4Way(in=w2, sel=sel[0..1], a=e, b=f, c=g, d=h);
  }
#+end_src

* Arithmetic logic unit

** Half adder

A half adder computes the sum of two bits and has the following truth
table:

#+name: Half adder truth table
| a | b | sum | carry |
|---+---+-----+-------|
| 0 | 0 |   0 |     0 |
| 1 | 0 |   1 |     0 |
| 0 | 1 |   1 |     0 |
| 1 | 1 |   0 |     1 |

As can be seen, this amounts to an ~Xor~ gate for the sum bit and an
~And~ gate for the carry bit:

#+name: Half adder
#+begin_src java
  CHIP HalfAdder {
      IN a, b;    // 1-bit inputs
      OUT sum,    // Right bit of a + b 
          carry;  // Left bit of a + b

      PARTS:
      Xor(a=a, b=b, out=sum);
      And(a=a, b=b, out=carry);
  }
#+end_src

** Full adder

A full adder computes the sum of two input bits, plus an incoming
carry bit (so three input bits). It has the following truth table:

#+name: Full adder truth table
| a | b | c | sum | carry |
|---+---+---+-----+-------|
| 0 | 0 | 0 |   0 |     0 |
| 0 | 1 | 0 |   1 |     0 |
| 1 | 0 | 0 |   1 |     0 |
| 1 | 1 | 0 |   0 |     1 |
| 0 | 0 | 1 |   1 |     0 |
| 0 | 1 | 1 |   0 |     1 |
| 1 | 0 | 1 |   0 |     1 |
| 1 | 1 | 1 |   1 |     1 |

This can be constructed using two half adders (hence the names half
and full adder), with an ~Or~ gate to determine the carry bit:

#+begin_src java
  CHIP FullAdder {
      IN a, b, c;  // 1-bit inputs
      OUT sum,     // Right bit of a + b + c
          carry;   // Left bit of a + b + c

      PARTS:
      HalfAdder(a=a, b=b, sum=i1, carry=i2);
      HalfAdder(a=c, b=i1, sum=sum, carry=i3);
      Or(a=i2, b=i3, out=carry);
  }
#+end_src

** 16-bit adder

Full adders can be chained together to produce a multi-bit adder; in
this case, we construct a 16-bit adder for our 16-bit computer:

#+begin_src java
  CHIP Add16 {
      IN a[16], b[16];
      OUT out[16];

      PARTS:
      HalfAdder(a=a[0], b=b[0], sum=out[0], carry=c1);
      FullAdder(a=a[1], b=b[1], c=c1, sum=out[1], carry=c2);
      FullAdder(a=a[2], b=b[2], c=c2, sum=out[2], carry=c3);
      FullAdder(a=a[3], b=b[3], c=c3, sum=out[3], carry=c4);
      FullAdder(a=a[4], b=b[4], c=c4, sum=out[4], carry=c5);
      FullAdder(a=a[5], b=b[5], c=c5, sum=out[5], carry=c6);
      FullAdder(a=a[6], b=b[6], c=c6, sum=out[6], carry=c7);
      FullAdder(a=a[7], b=b[7], c=c7, sum=out[7], carry=c8);
      FullAdder(a=a[8], b=b[8], c=c8, sum=out[8], carry=c9);
      FullAdder(a=a[9], b=b[9], c=c9, sum=out[9], carry=c10);
      FullAdder(a=a[10], b=b[10], c=c10, sum=out[10], carry=c11);
      FullAdder(a=a[11], b=b[11], c=c11, sum=out[11], carry=c12);
      FullAdder(a=a[12], b=b[12], c=c12, sum=out[12], carry=c13);
      FullAdder(a=a[13], b=b[13], c=c13, sum=out[13], carry=c14);
      FullAdder(a=a[14], b=b[14], c=c14, sum=out[14], carry=c15);
      FullAdder(a=a[15], b=b[15], c=c15, sum=out[15], carry=oflw);
  }
#+end_src

Note that in this design, the overflow (~oflw~) bit goes unused.

** 16-bit incrementer

We also define a special case of the 16-bit adder that simply
increments a number by 1:

#+begin_src java
  CHIP Inc16 {
      IN in[16];
      OUT out[16];

      PARTS:
      Add16(a=in, b[0]=true, b[1..15]=false, out=out);
  }
#+end_src

** ALU

We now have everything needed to construct the ALU:

#+begin_src java
  CHIP ALU {
      IN  
          x[16], y[16],  // 16-bit inputs        
          zx, // zero the x input?
          nx, // negate the x input?
          zy, // zero the y input?
          ny, // negate the y input?
          f,  // compute (out = x + y) or (out = x & y)?
          no; // negate the out output?
      OUT 
          out[16], // 16-bit output
          zr,      // if (out == 0) equals 1, else 0
          ng;      // if (out < 0)  equals 1, else 0

      PARTS:
      Mux16(a=x, b=false, sel=zx, out=i1);
      Not16(in=i1, out=i2);
      Mux16(a=i1, b=i2, sel=nx, out=i3);

      Mux16(a=y, b=false, sel=zy, out=i4);
      Not16(in=i4, out=i5);
      Mux16(a=i4, b=i5, sel=ny, out=i6);

      And16(a=i3, b=i6, out=i7);
      Add16(a=i3, b=i6, out=i8);
      Mux16(a=i7, b=i8, sel=f, out=i9);

      Not16(in=i9, out=i10);
      Mux16(a=i9, b=i10, sel=no, out[0..7]=i11, out[8..15]=i12, out=out, out[15]=ng);

      Or8Way(in=i11, out=i13);
      Or8Way(in=i12, out=i14);
      Or(a=i13, b=i14, out=i15);
      Not(in=i15, out=zr);
  }
#+end_src

By setting the six control pins to different combinations, the ALU
will perform different operations. 64 such combinations exist, but
only 18 are defined in the specification, as follows:

| zx | nx | zy | ny | f | no | out     |
|----+----+----+----+---+----+---------|
|  1 |  0 |  1 |  0 | 1 |  0 | 0       |
|  1 |  1 |  1 |  1 | 1 |  1 | 1       |
|  1 |  1 |  1 |  0 | 1 |  0 | -1      |
|  0 |  0 |  1 |  1 | 0 |  0 | x       |
|  1 |  1 |  0 |  0 | 0 |  0 | y       |
|  0 |  0 |  1 |  1 | 0 |  1 | !x      |
|  1 |  1 |  0 |  0 | 0 |  1 | !y      |
|  0 |  0 |  1 |  1 | 1 |  1 | -x      |
|  1 |  1 |  0 |  0 | 1 |  1 | -y      |
|  0 |  1 |  1 |  1 | 1 |  1 | x+1     |
|  1 |  1 |  0 |  1 | 1 |  1 | y+1     |
|  0 |  0 |  1 |  1 | 1 |  0 | x-1     |
|  1 |  1 |  0 |  0 | 1 |  0 | y-1     |
|  0 |  0 |  0 |  0 | 1 |  0 | x+y     |
|  0 |  1 |  0 |  0 | 1 |  1 | x-y     |
|  0 |  0 |  0 |  1 | 1 |  1 | y-x     |
|  0 |  0 |  0 |  0 | 0 |  0 | x&y     |
|  0 |  1 |  0 |  1 | 0 |  1 | x\vert​y |
