:PROPERTIES:
:Title: Build system
:Author: pjsamm
:Date: 2025-12-26
:END:

#+PROPERTY: header-args    :session
#+PROPERTY: header-args+   :results none
#+PROPERTY: header-args+   :tangle ../render.py

* Site build system

This build system generates a static site from Emacs [[https://orgmode.org/][Org]] files using
[[https://boisgera.github.io/pandoc/][Pandoc]] to convert said files to HTML, and [[https://jinja.palletsprojects.com/en/stable/][Jinja]] for generating pages
from templates.

We start by importing our dependencies and defining directories.

#+begin_src python
  import os
  import shutil
  import jinja2
  import pandoc

  PAGES_DIR = 'pages'
  STYLES_DIR = 'styles'
  TEMPLATES_DIR = 'templates'
  BUILD_DIR = 'build'
#+end_src

As mentioned, we will be using Pandoc to process our Org
files. However, the Python library uses various wrapper classes
(e.g. =Str=, =Space=, etc.) that will contaminate our output if we are
not careful. The following helper function unwraps the values in a
=Meta= object, leaving just the raw strings.

#+begin_src python
  def unwrap_metadata(metadata):
      # Unwrap 'Meta' object
      metadata = metadata[0]

      unwrapped = {}
      for k, v in metadata.items():
          # Unwrap 'MetaString' object
          unwrapped[k] = v[0]

      return unwrapped  
#+end_src

We also define a simple function for writing a string to a file.

#+begin_src python
  def write_to_file(fpath, s):
      with open(fpath, 'w+') as f:
          f.write(s)
#+end_src

Now, we create the build directory if it does not exist, then copy our
styles over.

#+begin_src python
  os.makedirs(BUILD_DIR, exist_ok=True)

  outdir = os.path.join(BUILD_DIR, STYLES_DIR)
  shutil.copytree(STYLES_DIR, outdir, dirs_exist_ok=True)
#+end_src

We also prepare a Jinja environment and load our templates.

#+begin_src python
  file_system_loader = jinja2.FileSystemLoader(TEMPLATES_DIR)
  jinja_env = jinja2.Environment(
      loader=file_system_loader,
      trim_blocks=True,
      lstrip_blocks=True
  )

  home_template = jinja_env.get_template('index.html')
  page_template = jinja_env.get_template('page.html')
#+end_src

We will now iterate through the site's pages and convert them to HTML
using Pandoc, collecting their metadata in =pages= for use on the home
page. Emacs likes to create backup files when editing, so we filter
files based on their extension.

#+begin_src python
  pages = []
  for dirpath, dirnames, filenames in os.walk(PAGES_DIR):
      for filename in filenames:
          fname, ext = os.path.splitext(filename)
          if ext != '.org':
              continue

          inpath = os.path.join(dirpath, filename)

          doc = pandoc.read(file=inpath)
          metadata = unwrap_metadata(doc[0])

          content = pandoc.write(doc, format='html')
          html = page_template.render(metadata, content=content)

          url = f'{fname}.html'
          outpath = os.path.join(BUILD_DIR, url)
          write_to_file(outpath, html)

          metadata['url'] = url
          pages.append(metadata)
#+end_src

Lastly, we generate the home page.

#+begin_src python
  html = home_template.render(title='Home', pages=pages)
  outpath = os.path.join(BUILD_DIR, 'index.html')
  write_to_file(outpath, html)
#+end_src
